name: Update Data
on:
  schedule:
    - cron: '*/15 0-14 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies and run main.py
      env:
        AMAP_KEY: ${{secrets.AMAP_KEY}}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python main.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Le Wang
        author_email: lewang.dev@gmail.com
        message: 'Commit by github action'
        add: '.'  
